import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { SC } from "./layout.styles";

const poppinsSans = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins-sans",
  weight: ["700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SC.Body
        className={`${poppinsSans.variable} ${poppinsSans.className} antialiased`}
      >
        {children}
      </SC.Body>
    </html>
  );
}
